name: Deploy to Vercel

on:
  push:
    branches:
      [main] # Executa o workflow ao fazer push na branch 'main'
  workflow_dispatch: # Permite execução manual do workflow

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      # Checkout do código
      - uses: actions/checkout@v3

      # Configurar o Python
      - uses: actions/setup-python@v3
        with:
          python-version: '3.9'
      
      # Instalar dependências
      - name: Install dependencies
        run: |
          pip install -r requirements.txt 
          pip install flake8 pytest mongomock
        
      # Rodar os testes
      - name: Run tests
        run: make test

  deploy:
    needs: test # O deploy só será executado se o job 'test' passar
    runs-on: ubuntu-latest

    steps:
      # Checkout do código
      - uses: actions/checkout@v3

      # Instalar o Vercel CLI
      - name: Install Vercel CLI
        run: npm install -g vercel

        # Fazer o deploy na Vercel
      - name: Deploy to Vercel
        env:
          VERCEL_TOKEN: ${{ secrets.VERCEL_CLI_KEY }} # Token de API armazenado nos Secrets
        run: |
          vercel --prod --token $VERCEL_TOKEN --yes